# Data Breach Insights Report - Docker Compose Configuration
# Provides PostgreSQL database for development and testing

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: breach-insights-db
    environment:
      POSTGRES_DB: breach_db
      POSTGRES_USER: breach_user
      POSTGRES_PASSWORD: breach_password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./data/sample_breaches.csv:/docker-entrypoint-initdb.d/sample_breaches.csv:ro
    networks:
      - breach_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U breach_user -d breach_db']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # pgAdmin (Optional - Database Management UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: breach-insights-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@breach-insights.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - breach_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - admin # Only start with --profile admin

  # Jupyter Notebook (Optional - Data Analysis Environment)
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: breach-insights-jupyter
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      JUPYTER_TOKEN: breach-insights-2024
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks:rw
      - ./data:/home/jovyan/work/data:ro
      - ./sql:/home/jovyan/work/sql:ro
      - ./scripts:/home/jovyan/work/scripts:ro
    networks:
      - breach_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - analysis # Only start with --profile analysis

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  breach_network:
    driver: bridge
# Usage Examples:
#
# Start only PostgreSQL:
#   docker-compose up postgres
#
# Start PostgreSQL + pgAdmin:
#   docker-compose --profile admin up
#
# Start PostgreSQL + Jupyter:
#   docker-compose --profile analysis up
#
# Start everything:
#   docker-compose --profile admin --profile analysis up
#
# Load sample data:
#   python scripts/ingest_csv_to_postgres.py --db postgresql://breach_user:breach_password@localhost:5432/breach_db
#
# Access pgAdmin:
#   http://localhost:8080
#   Email: admin@breach-insights.local
#   Password: admin123
#
# Access Jupyter:
#   http://localhost:8888
#   Token: breach-insights-2024
